### ISSUE TITLE
Data not working as intended?

### ISSUE THREAD

**Issue by yasin-mesut** [radiocity/twig-html-loader#13]
Hey there,

I'm not sure if I'm trying to use data option correctly or not but I'm running into some issues. I've been following the readme and I'm using data as this right now:

```
const data = path.join(contextPath, `${name}.json`);
context.addDependency(data); // Force webpack to watch file
return context.fs.readJsonSync(data, { throws: false }) || {};
```

This seems to work properly since I get the correctly rendered html string inside my webpack bundle. However, I can not use this for including a `.twig ` file into my `index.twig`.

Using `{% include '@components[name].twig' %}` works but it only includes the plain `.twig` file without its corresponding data. These are not known to any `.twig` file. Only webpack knows about that. Yet I still couldn't figure out a way to get the string out of my webpack bundle and use it in my rendered `index.html`.

Am I missing something here? Or is this an intended behaviour? I'd really like to get my rendered templates into my `index.html`.

**Comment by radiocity** [comment]
Could you show any `@components[name].twig` that doesn\`t get data? 
Twig has some limitations with variables inside `macro` and `block` tags.

**Comment by yasin-mesut** [comment]
I'll add some more specific code tomorrow since I don't have it here right now. The problem is basically that using the example provided in the readme doesn't give me the result I'm expecting. Quick example.

Adding the following line into any JS-file (e.g. main.js) imports the rendered html string into my webpack bundle.

`var html = require('./index.twig');`

This results in having my data beeing bound correctly, but puts everything into my bundle. That said, I don't have any option to include the rendered string (including the data) to my rendered ìndex.html`.

I may be wrong about the use case but is this supposed to be like that? Can't I include the rendered html into my markup? Or do I have to use some other loader/plugin for that?

**Comment by radiocity** [comment]
Use `html-webpack-plugin` to generate html file from twig. You don\`t need `var html = require('./index.twig');` at all.

```js
// webpack.config.js
const glob = require('glob');
const path = require('path');

const HTMLWebpackPlugin = require('html-webpack-plugin');

const generateHTMLPlugins = () =>
  glob.sync('./src/**/*.twig').map(
    dir =>
      new HTMLWebpackPlugin({
        filename: path.basename(dir).replace('.twig', '.html'), // Output
        template: dir, // Input
      }),
  );

module.exports = {
  node: {
    fs: 'empty',
  },
  entry: ['./src/dummy.js'],
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'app.bundle.js',
  },
  module: {
    rules: [
      {
        test: /\.twig$/,
        use: [
          'raw-loader',
          {
            loader: 'twig-html-loader',
            options: {
              namespaces: {
                'layouts': path.join(__dirname, 'src/layouts/'),
                'components': path.join(__dirname, 'src/components'),
                'svg': path.join(__dirname, 'src/svg'),
              },
              data: {
                test: "Lorem ipsum dolor sit amen"
              }
            },
          },
        ],
      },
    ],
  },
  plugins: [
    ...generateHTMLPlugins(),
  ],
};
```

Hope, I get into your problem at this time 😇

**Comment by yasin-mesut** [comment]
Thanks for your response so far! It seems like your example doesn't work in my environment. Not sure if it's because I'm using webpack 4. However, I've prepared a minimal repo for showcasing my problem. See [here](https://github.com/yasin-mesut/twig-test).

I'll try again explaining what we are trying to achieve. What we want is to use `html-twig-loader` to generate html markup which also holds the rendered data, provided by the data option through the loader itself. The problem now is that our bundled JS file (`dist/js/main.js`) does hold the correct html string even with the correct data. We now want to use that html in our `index.twig`(renders to `dist/index.html`). Including the component (`helloWorld.twig`) itself in `index.twig` results in a new import which is resolved by twig.js and doesn't fit our needs. That said, we would like to know a way on how to include rendered html markup (including the correct data) in `index.twig`.

Note: As explained, including through twig works as expected. The problem in here is we only get the data which is set in the global scope and not in the components scope. You can see that pretty well if you compare `webpack.config.js` with the final output in `dist/index.html` and `dist/js/main.js`.

**Comment by radiocity** [comment]
Why should the result be the same if you send different data depending on the context?

For `index.js` context is everithing you requires inside it (`helloWorld.twig`) and for `index.twig` —  `index.twig` only.

The console output is misleading. Comment require string in `index.js` and you going to notice the difference.

<details><summary>webpack.config.js (original)</summary>
<p>

```js
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

module.exports = {
  mode: 'development',
  entry: {
    main: './src/index.js',
  },
  output: {
    publicPath: '/assets/',
    filename: 'js/[name].js',
  },
  module: {
    rules: [{
      test: /\.twig$/,
      use: [
        'raw-loader',
        {
          loader: 'twig-html-loader',
          options: {
            namespaces: {
              'components': path.join(__dirname, 'src', 'components'),
            },
            data: (context) => {
              const contextPath = context.context;
              const name = contextPath.split(path.sep).pop();
              const alias = `${path.sep}components${path.sep}`;

              console.log('context path ', contextPath);

              if (contextPath.includes(alias)) {
                const data = path.join(contextPath, `${name}.json`);
                console.log('asdfasdfasdf ', data);
                context.addDependency(data); // Force webpack to watch file

                return context.fs.readJsonSync(data, { throws: false }) || {};
              } else {
                return {
                  message: 'global hello world'
                };
              }
            }
          }
        }
      ]
    }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.twig',
    }),
  ]
};
```

</p>
</details>

P.S. Do not use `/` as path separator. There is a [`path.sep`](https://nodejs.org/api/path.html#path_path_sep) variable.

**Comment by yasin-mesut** [comment]
Thanks for your response. The separation in different contexts is correct. I already know that. The question in here right now is, is there any way to use `helloWorld.twig`  (including the data within its own context) in `index.twig`?

**Comment by radiocity** [comment]
Add custom function [include()](https://twig.symfony.com/doc/2.x/functions/include.html) and pass json data straight to local variable in `helloWorld.twig`.  Unfortunately, the twigjs does [not support](https://github.com/twigjs/twig.js/issues/392) it out of the box. 
It seems better to add this feature to a [future version](https://github.com/radiocity/twig-html-loader/projects/5).

**Comment by yasin-mesut** [comment]
Thanks so far for all the information. Helped a lot. 😃
