### ISSUE TITLE
Named parameters

### ISSUE THREAD

**Issue by st-schneider** [radiocity/twig-html-loader#20]
I guess this might even be a but with twigjs in general. Currently templates that have something like `{{ theme_asset('path/to/asset', version = asset_reset) }}` does not work and exits with parsing error

**Comment by radiocity** [comment]
Would you mind to add error message here?

**Comment by st-schneider** [comment]
Here you go
```
Module build failed (from ./node_modules/twig-html-loader/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) TwigException: Unable to parse '= asset_reset' at template position38
```

**Comment by radiocity** [comment]
More like a twigjs bug
https://github.com/twigjs/twig.js/issues/410

**Comment by st-schneider** [comment]
:(
