### ISSUE TITLE
TwigException: include function does not exist and is not defined in the context

### ISSUE THREAD

**Issue by sylvainbaronnet** [radiocity/twig-html-loader#21]
hi, 

the loader : 

```
const twig = {
  test: /\.twig$/,
  use: [
    'raw-loader',
    {
      loader: 'twig-html-loader',
      options: {
        data: context => {
          const data = path.join(__dirname, 'data.json');
          context.addDependency(data); // Force webpack to watch file
          return context.fs.readJsonSync(data, {throws: false}) || {};
        },
      },
    },
  ],
};
```

used with : 
```
const generateHTMLPlugins = () =>
  glob.sync('./src/pages/**/*.twig').map(dir => {
    const filename = path.basename(dir);

    return new HTMLWebpackPlugin({
      filename: filename.replace('twig', 'html'),
      template: path.join(config.root, config.paths.src + '/pages', filename),
    });
  });
```

and the templage : 
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    {{ include('../partials/header.twig') }}

  </body>
</html>
```
thanks in advance for your help!

**Comment by radiocity** [comment]
https://github.com/radiocity/twig-html-loader/issues/13#issuecomment-479863373

**Comment by jimblue** [comment]
Hello @radiocity !

I'm getting the exact same issue and I comment 13 con't help at all.

I'm not passing data trough I only want to use Twig include method.

**Comment by Mellis84** [comment]
I managed to fix that error by having includes using this syntax:
`{% include '@components/_header.twig' %}`

rather than
`{{ include('@components/_header.twig') }}`

Hope this helps! @jimblue @radiocity

**Comment by t6nut** [comment]
I can't use "traditional php function" with fn = `{% if fn('is_single') %}` - is it possible to bypass it? Or is there a twig alternative to check if the page is a single post? Can't seem to find any syntax for this..
