### ISSUE TITLE
Relative base views folder

### ISSUE THREAD

**Issue by besimhu** [radiocity/twig-html-loader#4]
Directory setup:

**| partials**
| --header.html
| --header.html
**| layouts**
| --base.html

Is there a way to write `{% include "partials/header.html" %}` inside my base.html file without having to do `{% include "./../partials/header.html" %}`

[gulp-twig](https://www.npmjs.com/package/gulp-twig) has a base option to set extends/includes relative to the defined option

**Comment by radiocity** [comment]
Look at [configuration](https://github.com/radiocity/twig-html-loader/issues/1#issuecomment-430824357) from previous issue. Following template includes partials successfully:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Twig test</title>
</head>
<body>
  {% include '_partials/_footer.twig' %}
</body>
</html>
```

**Comment by besimhu** [comment]
That works if it is an index file form root. But if I were to have nested pages, it no longer works as I now need to backtrack the path.

(Had looked at the link before for the glob solution)

**Comment by radiocity** [comment]
Still [everything](https://gist.github.com/radiocity/620e89b17778b5466719402e36c1747c) works. 
**test.html** compiles into the same folder as **index.html**.

**Comment by piotrmerton** [comment]
Yes it works all right, but would it be possible to set via options equivalent of defined base "views" path like in PHP environment? Thus referencing partials from nested files wouldn't require "../". Now all files must be referenced relatively to the template file itself.

I'm refering "Namespaces" mentioned https://github.com/twigjs/twig.js/wiki 

> When referencing another template, instead of using the relative path you can use the namespaces that were previously defined.
