### ISSUE TITLE
Webpack rebuild with options data update

### ISSUE THREAD

**Issue by besimhu** [radiocity/twig-html-loader#5]
My current options look like this:

```
options: {
  data: {
    options: require( path.join(__dirname, '/src/html/_data/options.json') ),
    global: require( path.join(__dirname, '/src/html/_data/global.json') ),
  }
}
```

Is there a way to recompile webpack when one of the json files changes? I can watch for file changes with devserver, but that will not rebuild what's in memory already.

**Comment by radiocity** [comment]
No. There is no such functionality in loader at this moment.

**Comment by radiocity** [comment]
@besimhu, how do you watch for file changes?

**Comment by besimhu** [comment]
@radiocity at the moment I am watching through devServer `contentBase` and `watchContentBase`

```js
contentBase: path.join(__dirname, 'dist'),
watchContentBase: true
```

**Comment by radiocity** [comment]
Looks like only way is to add watch option into loader and allow data to be a function

**Comment by radiocity** [comment]
Required functionality added in 0.1.4 (5a2a4cf)
Check [example](https://github.com/radiocity/twig-html-loader#watch-data-from-files)

**Comment by wpsix** [comment]
@radiocity Is it possible to use your solution with multiple json files?

**Comment by radiocity** [comment]
In most cases, yes.
