### ISSUE TITLE
data option could be a function

### ISSUE THREAD

**Issue by ryuran** [radiocity/twig-html-loader#6]
Data option is currently an object.
I would be able to get a `json` related to the current twig file as `data`
So I need a function with current file path as a parameter.
Could it be possible ?

**Comment by radiocity** [comment]
Yes. Under construction.

**Comment by radiocity** [comment]
https://github.com/radiocity/twig-html-loader/issues/5

**Comment by radiocity** [comment]
Released in 0.1.4 (5a2a4cf)
