### ISSUE TITLE
Why use raw-loader ?

### ISSUE THREAD

**Issue by ryuran** [radiocity/twig-html-loader#8]
I do not uderstand why we need to use raw-loader.
What part of the job `twig-html-loader` and `raw-loader` do?

**Comment by radiocity** [comment]
None of any job.
It is a result of brainless copy-paste. The idea is user able to combine twig-html-loader with other (ex, html-loader)

**Comment by ryuran** [comment]
Ok I understand now I'm looking for a way to transfert data from HTMLWebpackPlugin to twig file #9.

It's easier with `render-template-loader` or `twig-loader` but it's not compatible with `html-loader`.
